export class TrnCollectionPaymentModel {
    Id: number = 0;
    CollectionId: number = 0;
    CollectionDate: string = "";
    CollectionManualNumber: string = "";
    CollectionCustomer: string = "";
    CollectionPreparedBy: string = "";
    SoldUnitId: number = 0;
    SoldUnit: string = "";
    SoldUnitEquityScheduleId: number = 0;
    SoldUnitEquitySchedule: string = "";
    Project: string = "";
    PayType: string = "";
    Amount: number = 0;
    Agent: string = "";
    Broker: string = "";
    CheckNumber: string = "";
    CheckDate: string = "";
    CheckBank: string = "";
    OtherInformation: string = "";
}